///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class faqDataFaqs {
/*
{
  "question": "How accurate are the prices you display?",
  "answer": "We strive to keep our prices as accurate as possible by: ..."
}
*/

  String? question;
  String? answer;

  faqDataFaqs({
    this.question,
    this.answer,
  });
  faqDataFaqs.fromJson(Map<String, dynamic> json) {
    question = json['question']?.toString();
    answer = json['answer']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['question'] = question;
    data['answer'] = answer;
    return data;
  }
}

class faqData {
/*
{
  "categoryName": "Top Questions",
  "faqs": [
    {
      "question": "How accurate are the prices you display?",
      "answer": "We strive to keep our prices as accurate as possible by: ..."
    }
  ]
}
*/

  String? categoryName;
  List<faqDataFaqs?>? faqs;

  faqData({
    this.categoryName,
    this.faqs,
  });
  faqData.fromJson(Map<String, dynamic> json) {
    categoryName = json['categoryName']?.toString();
    if (json['faqs'] != null) {
      final v = json['faqs'];
      final arr0 = <faqDataFaqs>[];
      v.forEach((v) {
        arr0.add(faqDataFaqs.fromJson(v));
      });
      faqs = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['categoryName'] = categoryName;
    if (faqs != null) {
      final v = faqs;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['faqs'] = arr0;
    }
    return data;
  }
}

class faq {
/*
{
  "data": [
    {
      "categoryName": "Top Questions",
      "faqs": [
        {
          "question": "How accurate are the prices you display?",
          "answer": "We strive to keep our prices as accurate as possible by: ..."
        }
      ]
    }
  ]
}
*/

  List<faqData?>? data;

  faq({
    this.data,
  });
  faq.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <faqData>[];
      v.forEach((v) {
        arr0.add(faqData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
