///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubCategoriesDataChildCategories {
/*
{
  "_id": "65b77840503d2e949a166283",
  "name": "Smartphones",
  "parentCategory": "65b7783f503d2e949a166277",
  "createdAt": "2024-01-29T10:04:48.323Z",
  "updatedAt": "2024-01-29T10:04:48.324Z",
  "__v": 0,
  "index": 0
}
*/

  String? Id;
  String? name;
  String? parentCategory;
  String? createdAt;
  String? updatedAt;
  int? V;
  int? index;

  SubCategoriesDataChildCategories({
    this.Id,
    this.name,
    this.parentCategory,
    this.createdAt,
    this.updatedAt,
    this.V,
    this.index,
  });
  SubCategoriesDataChildCategories.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    name = json['name']?.toString();
    parentCategory = json['parentCategory']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
    index = json['index']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['name'] = name;
    data['parentCategory'] = parentCategory;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    data['index'] = index;
    return data;
  }
}

class SubCategoriesData {
/*
{
  "_id": "65b7783f503d2e949a166277",
  "name": "Mobile Phones and Accessories",
  "parentCategory": "65b7783e503d2e949a166270",
  "createdAt": "2024-01-29T10:04:47.285Z",
  "updatedAt": "2024-01-29T10:04:47.286Z",
  "__v": 0,
  "childCategories": [
    {
      "_id": "65b77840503d2e949a166283",
      "name": "Smartphones",
      "parentCategory": "65b7783f503d2e949a166277",
      "createdAt": "2024-01-29T10:04:48.323Z",
      "updatedAt": "2024-01-29T10:04:48.324Z",
      "__v": 0,
      "index": 0
    }
  ],
  "numChildCategories": 2
}
*/

  String? Id;
  String? name;
  String? parentCategory;
  String? createdAt;
  String? updatedAt;
  int? V;
  List<SubCategoriesDataChildCategories?>? childCategories;
  int? numChildCategories;

  SubCategoriesData({
    this.Id,
    this.name,
    this.parentCategory,
    this.createdAt,
    this.updatedAt,
    this.V,
    this.childCategories,
    this.numChildCategories,
  });
  SubCategoriesData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    name = json['name']?.toString();
    parentCategory = json['parentCategory']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
    if (json['childCategories'] != null) {
      final v = json['childCategories'];
      final arr0 = <SubCategoriesDataChildCategories>[];
      v.forEach((v) {
        arr0.add(SubCategoriesDataChildCategories.fromJson(v));
      });
      childCategories = arr0;
    }
    numChildCategories = json['numChildCategories']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['name'] = name;
    data['parentCategory'] = parentCategory;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    if (childCategories != null) {
      final v = childCategories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['childCategories'] = arr0;
    }
    data['numChildCategories'] = numChildCategories;
    return data;
  }
}

class SubCategories {
/*
{
  "data": [
    {
      "_id": "65b7783f503d2e949a166277",
      "name": "Mobile Phones and Accessories",
      "parentCategory": "65b7783e503d2e949a166270",
      "createdAt": "2024-01-29T10:04:47.285Z",
      "updatedAt": "2024-01-29T10:04:47.286Z",
      "__v": 0,
      "childCategories": [
        {
          "_id": "65b77840503d2e949a166283",
          "name": "Smartphones",
          "parentCategory": "65b7783f503d2e949a166277",
          "createdAt": "2024-01-29T10:04:48.323Z",
          "updatedAt": "2024-01-29T10:04:48.324Z",
          "__v": 0,
          "index": 0
        }
      ],
      "numChildCategories": 2
    }
  ]
}
*/

  List<SubCategoriesData?>? data;

  SubCategories({
    this.data,
  });
  SubCategories.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <SubCategoriesData>[];
      v.forEach((v) {
        arr0.add(SubCategoriesData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
