// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd0WhhcEXvR7HIwgPZ8CiiKV9jnbwugME',
    appId: '1:546453705130:web:5f1d6d1b18a86ed6565bd3',
    messagingSenderId: '546453705130',
    projectId: 'price-butlers-llc-c31ed',
    authDomain: 'price-butlers-llc-c31ed.firebaseapp.com',
    databaseURL: 'https://price-butlers-llc-c31ed-default-rtdb.firebaseio.com',
    storageBucket: 'price-butlers-llc-c31ed.appspot.com',
    measurementId: 'G-7QGDVXRNWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuMkzaTxDyjejIYl0bkTzdjtsaTIzwCNY',
    appId: '1:546453705130:android:447db449a3617c6b565bd3',
    messagingSenderId: '546453705130',
    projectId: 'price-butlers-llc-c31ed',
    databaseURL: 'https://price-butlers-llc-c31ed-default-rtdb.firebaseio.com',
    storageBucket: 'price-butlers-llc-c31ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcTSKO4jD69sst87LQRDRf3x2k3iZD3Y',
    appId: '1:546453705130:ios:450fdae20aa27859565bd3',
    messagingSenderId: '546453705130',
    projectId: 'price-butlers-llc-c31ed',
    databaseURL: 'https://price-butlers-llc-c31ed-default-rtdb.firebaseio.com',
    storageBucket: 'price-butlers-llc-c31ed.appspot.com',
    iosClientId: '546453705130-bu94p3v9hsih53jkcmqj2sjmbl5809gf.apps.googleusercontent.com',
    iosBundleId: 'com.example.pricebutler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmcTSKO4jD69sst87LQRDRf3x2k3iZD3Y',
    appId: '1:546453705130:ios:79678f8f48ecafc0565bd3',
    messagingSenderId: '546453705130',
    projectId: 'price-butlers-llc-c31ed',
    databaseURL: 'https://price-butlers-llc-c31ed-default-rtdb.firebaseio.com',
    storageBucket: 'price-butlers-llc-c31ed.appspot.com',
    iosClientId: '546453705130-5k2us9vd0c62866cjnmgg1jc9qeoi0uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pricebutler.RunnerTests',
  );
}
